# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/carlo/Downloads/project_5/project_5.cache/wt [current_project]
set_property parent.project_path C:/Users/carlo/Downloads/project_5/project_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/carlo/Downloads/project_5/project_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/carlo/Downloads/project_5/mem.coe
add_files -quiet c:/Users/carlo/Downloads/project_5/project_5.srcs/sources_1/ip/mem/mem.dcp
set_property used_in_implementation false [get_files c:/Users/carlo/Downloads/project_5/project_5.srcs/sources_1/ip/mem/mem.dcp]
read_verilog -library xil_defaultlib -sv C:/Users/carlo/Downloads/project_5/project_5.srcs/sources_1/new/BMEM_GCD_SPI_Wrapper.sv
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top BMEM_GCD_SPI_Wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef BMEM_GCD_SPI_Wrapper.dcp

catch { report_utilization -file BMEM_GCD_SPI_Wrapper_utilization_synth.rpt -pb BMEM_GCD_SPI_Wrapper_utilization_synth.pb }
