# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.srcs/sources_1/bd/my_test_mem/ip/my_test_mem_dist_mem_gen_0_0/my_test_mem_dist_mem_gen_0_0.xci
# IP: The module: 'my_test_mem_dist_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.srcs/sources_1/bd/my_test_mem/ip/my_test_mem_dist_mem_gen_0_0/my_test_mem_dist_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_test_mem_dist_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.srcs/sources_1/bd/my_test_mem/ip/my_test_mem_dist_mem_gen_0_0/my_test_mem_dist_mem_gen_0_0.xci
# IP: The module: 'my_test_mem_dist_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.srcs/sources_1/bd/my_test_mem/ip/my_test_mem_dist_mem_gen_0_0/my_test_mem_dist_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_test_mem_dist_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
