# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_8/port3116-440-p8-attempt2/project_8_3/project_8_3.srcs/sources_1/ip/gene_mem/gene_mem.xci
# IP: The module: 'gene_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_8/port3116-440-p8-attempt2/project_8_3/project_8_3.srcs/sources_1/ip/gene_mem/gene_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gene_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_8/port3116-440-p8-attempt2/project_8_3/project_8_3.srcs/sources_1/ip/gene_mem/gene_mem.xci
# IP: The module: 'gene_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_8/port3116-440-p8-attempt2/project_8_3/project_8_3.srcs/sources_1/ip/gene_mem/gene_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gene_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
