# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/port3116/Desktop/lab_6/project_6/project_6.srcs/sources_1/ip/mem/mem.xci
# IP: The module: 'mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/port3116/Desktop/lab_6/project_6/project_6.srcs/sources_1/ip/mem/mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/port3116/Desktop/lab_6/project_6/project_6.srcs/sources_1/ip/mem/mem.xci
# IP: The module: 'mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/port3116/Desktop/lab_6/project_6/project_6.srcs/sources_1/ip/mem/mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
