# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.cache/wt} [current_project]
set_property parent.project_path {C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.srcs/sources_1/bd/my_test_mem/ip/my_test_mem_dist_mem_gen_0_0/my_test_mem_dist_mem_gen_0_0.coe}}
read_verilog -library xil_defaultlib -sv {{C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.srcs/sources_1/new/memory_cir.sv}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.srcs/constrs_1/imports/lab_4/ZYBO_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/carlo/OneDrive - University of Idaho/UofI_19-20/Spring_2020/ECE_440/lab_4/project_4/project_4.srcs/constrs_1/imports/lab_4/ZYBO_Master.xdc}}]


synth_design -top memory_cir -part xc7z010clg400-1


write_checkpoint -force -noxdef memory_cir.dcp

catch { report_utilization -file memory_cir_utilization_synth.rpt -pb memory_cir_utilization_synth.pb }
